events {
    worker_connections 1024;
}

http {
   include /opt/homebrew/etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    upstream user_service {
        server 127.0.0.1:3001;
    }

    upstream captain_service {
        server 127.0.0.1:3002;
    }

    upstream ride_service {
        server 127.0.0.1:3003;
    }

    # socket.io nodes setup for ip_hash (required for polling)
    # The services themselves are hosting socket.io on their respective ports.
    upstream socket_nodes {
        ip_hash;
        server 127.0.0.1:3001;
        server 127.0.0.1:3002;
        server 127.0.0.1:3003;
    }

    server {
        listen 3000;
        
        # Cross-Origin Resource Sharing (CORS) headers for the Gateway
        # Normally microservices handle them, but Nginx can provide them as well if needed.
        
        location /users/ {
            proxy_pass http://user_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /captain/ {
            proxy_pass http://captain_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /rides/ {
            proxy_pass http://ride_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /socket.io/ {
            proxy_pass http://socket_nodes/socket.io/;
            # WebSocket Support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            
            # Identify forwarding
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
